## Problem 1:

    Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:
    a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
    b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
    Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b, your output should contain only one 2 even if array a contains more than one 2 within it.

In [57]:
import numpy as np
import pandas as pd

In [58]:
# Given the two arrays
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Using np.intersect1d to find the distinct common elements 
unique_items = np.intersect1d(a, b)

# Print the result
print("Common Elements:")
print(unique_items)

Common Elements:
[2 4]


## Problem 2:

    Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
    so that you do not need to explicitly key in every integer value.
    1   6    11
    2   7    12
    3   8    13
    4   9    14
    5   10   15

In [59]:
# Create a sequence of numbers from 1 to 15 (inclusive)
# np.arange(start, stop)
sequence = np.arange(1, 16)

# Reshape into a 5x3 array.
# By default, reshape fills row by row ( 1  2  3).
# To fill column by column as per your example, we use 'order='F'' (for Fortran-style order).
result_array = sequence.reshape((5, 3), order='F')

# Print the resulting array
print("5x3 Array:")
print(result_array)

5x3 Array:
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


## Problem 3:

    The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. 
    Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows:
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15

In [60]:
# Transform result_array into a unidimensional array (flattening)
# We use order='F' agin to do (column-major) order
unidimensional_array = result_array.flatten(order='F')

# Print the flattened array
print("Unidimensional Array:")
print(unidimensional_array)

Unidimensional Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


## Problem 4:

    Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, 
    the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.

In [61]:
# Reshape unidimensional_array into a 3-dimensional array
# use reshape into 3 col with 5 rows with 1 element each
into_3d_array = unidimensional_array.reshape((3, 5, 1))

# Print the 3D array
print("3D Array:")
print(into_3d_array)

3D Array:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]

 [[11]
  [12]
  [13]
  [14]
  [15]]]


## Problem 5:

    Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.


In [62]:
# Flatten the 3-D array into a 2-D sequence
flat_sequence = into_3d_array.flatten()
flat_2d_array = flat_sequence.reshape((5, 3), order='F')

# Print 2D Array
print("2D Array:")
print(flat_2d_array)

2D Array:
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


## Problem 6:

    You are given the following two arrays:
    a = np.array([12, 5, 7, 15, 3, 1, 8])
    b = np.array([14, 6, 3, 11, 19, 12, 5])
    Write a Python/Numpy code block that removes from array a any items that are also present in array b.

In [63]:
# Given two arrays
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

# Using np.setdiff1d to find elements in 'a' that are NOT in 'b'
remove_array = np.setdiff1d(a, b)

# Print the resulting array
print("Unqiue array:")
print(remove_array)

Unqiue array:
[ 1  7  8 15]


## Problem 7:
    Answer the following questions about the accompanying data file.

    What is the maximum yearly NYC consumption of water in millions of gallons per day?
    How many calendar years are represented within this data set? NumPy's shape command is one way to find out.
    What is the mean and the standard deviation of the per capita daily water consumption?
    What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [64]:
file_path = 'Module6_Data.csv'
# Import the data into a pandas DataFrame
try:
    df = pd.read_csv(file_path)
    print(df)
except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found.")

    Year  New York City Population  NYC Consumption(Million gallons per day)  \
0   1979                 7102100.0                                    1512.0   
1   1980                 7071639.0                                    1506.0   
2   1981                 7089241.0                                    1309.0   
3   1982                 7109105.0                                    1382.0   
4   1983                 7181224.0                                    1424.0   
5   1984                 7234514.0                                    1465.0   
6   1985                 7274054.0                                    1326.0   
7   1986                 7319246.0                                    1351.0   
8   1987                 7342476.0                                    1447.0   
9   1988                 7353719.0                                    1484.0   
10  1989                 7344175.0                                    1402.0   
11  1990                 7335650.0      

### What is the `maximum` yearly NYC consumption of water in millions of gallons per day?


In [65]:
nyc_consumption = 'NYC Consumption(Million gallons per day)'

# Finding the maximum consumption
max_consumption = df[nyc_consumption].max()

print(f"Maximum yearly NYC consumption of water: {max_consumption:.2f} Million Gallons per Day")

Maximum yearly NYC consumption of water: 1512.00 Million Gallons per Day


### How many `calendar years` are represented within this data set? NumPy's shape command is one way to find out.


In [66]:
# Getting the number of rows which represents the number of years
num_years = df.shape[0]

print(f"Number of calendar years represented in the data set: {num_years}")

Number of calendar years represented in the data set: 39


### What is the mean and the `standard deviation` of the per capita daily water consumption?


In [67]:
per_capita_col = 'Per Capita(Gallons per person per day)'
# Calculate the mean
mean_per_capita = df[per_capita_col].mean()

# Calculate the standard deviation
std_dev_per_capita = df[per_capita_col].std()

print(f"Mean per capita daily water consumption: {mean_per_capita:.2f} Gallons")
print(f"Standard deviation of per capita daily water consumption: {std_dev_per_capita:.2f} Gallons")

Mean per capita daily water consumption: 160.31 Gallons
Standard deviation of per capita daily water consumption: 31.93 Gallons


### What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

In [68]:
nyc_population = 'New York City Population'

# Use NumPy's diff function to calculate the year-to-year differences in population
pop_diff = np.diff(df[nyc_population])

print("Increase or decrease in population from year to year:")
print(pop_diff)

Increase or decrease in population from year to year:
[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
